// ============================================================
// File: BattleTextRenderer.h
// Responsibility: Screen-space text rendering for battle UI.
//
// Wraps DirectXTK SpriteFont + SpriteBatch to draw UTF-8 / ASCII strings
// at pixel positions.  Intended for HUD labels that do NOT need world-space
// transforms (enemy names, damage numbers, status text).
//
// Usage (shared across renderers in BattleState):
//   1. BattleState creates and owns one BattleTextRenderer by value.
//   2. Initialize() is called once in BattleState::OnEnter().
//   3. Any renderer that needs text receives a BattleTextRenderer* ref
//      and calls DrawStringCentered() / DrawString() inside its Render pass.
//   4. Shutdown() is called in BattleState::OnExit() before D3DContext teardown.
//
// Render contract:
//   DrawString / DrawStringCentered open a SpriteBatch Begin/End internally.
//   Each call is one Begin/End pair — callers must NOT nest their own Begin.
//   For performance, batch multiple strings by collecting them and calling
//   BeginBatch() ... DrawStringRaw() ... EndBatch() manually.
//
// Font file:
//   Loaded from assets/fonts/arial_16.spritefont (generated by MakeSpriteFont).
//   To change font size or typeface, regenerate the .spritefont file and update
//   the path passed to Initialize().
//
// Ownership:
//   BattleState owns one BattleTextRenderer by value (no heap allocation).
//   GPU resources (SpriteFont texture atlas, SpriteBatch buffers) are released
//   in Shutdown().
//
// Common mistakes:
//   1. Calling DrawString before Initialize() — SpriteFont is null, crash.
//   2. Calling DrawString inside another SpriteBatch Begin/End — nested Begin
//      throws std::logic_error in DirectXTK debug builds.
//   3. Not calling BindViewport() before Begin() — SpriteBatch throws when
//      the RS stage has no viewport (happens after WorldSpriteRenderer resets it).
// ============================================================
#pragma once
#include <d3d11.h>
#include <wrl/client.h>
#include <SpriteBatch.h>
#include <SpriteFont.h>
#include <CommonStates.h>
#include <DirectXMath.h>
#include <memory>
#include <string>

class BattleTextRenderer
{
public:
    // ----------------------------------------------------------------
    // Initialize
    // Purpose:
    //   Load the SpriteFont atlas from disk and create the SpriteBatch +
    //   CommonStates objects.
    //
    // Parameters:
    //   device/context  — D3D11 device and immediate context
    //   fontPath        — wide-string path to the .spritefont file
    //                     (e.g. L"assets/fonts/arial_16.spritefont")
    //   screenW/H       — render target dimensions for viewport binding
    //
    // Returns true on success.  On failure, IsReady() returns false and
    // all Draw calls are no-ops.
    // ----------------------------------------------------------------
    bool Initialize(ID3D11Device*       device,
                    ID3D11DeviceContext* context,
                    const std::wstring& fontPath,
                    int screenW, int screenH);

    // ----------------------------------------------------------------
    // DrawString
    // Purpose:
    //   Draw a single ASCII/UTF-8 string at (x, y) in screen pixels.
    //   Opens its own SpriteBatch Begin/End pair — do NOT call from inside
    //   another Begin/End.
    //
    // Parameters:
    //   context — immediate device context for this frame
    //   text    — null-terminated string to draw
    //   x, y    — top-left pixel position on screen
    //   color   — RGBA tint (default: opaque white)
    // ----------------------------------------------------------------
    void DrawString(ID3D11DeviceContext*        context,
                    const char*                 text,
                    float                       x,
                    float                       y,
                    DirectX::FXMVECTOR          color = DirectX::Colors::White,
                    DirectX::CXMMATRIX          transform = DirectX::XMMatrixIdentity());

    // ----------------------------------------------------------------
    // DrawStringCentered
    // Purpose:
    //   Draw a string horizontally centered around (centerX, y).
    //   Measures the string width via SpriteFont::MeasureString() first,
    //   then shifts the origin so the text is perfectly centered.
    //
    // Parameters:
    //   Same as DrawString except centerX is the desired center X pixel.
    // ----------------------------------------------------------------
    void DrawStringCentered(ID3D11DeviceContext* context,
                            const char*          text,
                            float                centerX,
                            float                y,
                            DirectX::FXMVECTOR   color = DirectX::Colors::White,
                            DirectX::CXMMATRIX   transform = DirectX::XMMatrixIdentity());

    // ----------------------------------------------------------------
    // BeginBatch / DrawStringRaw / EndBatch
    // Purpose:
    //   Low-level API for drawing multiple strings in a single Begin/End
    //   pair (lower GPU state-change overhead than repeated DrawString).
    //
    //   Call order per frame:
    //     BeginBatch(ctx);
    //     DrawStringRaw(ctx, "foo", x, y);
    //     DrawStringRaw(ctx, "bar", x2, y2);
    //     EndBatch();
    //
    // WARNING: Do NOT mix with DrawString / DrawStringCentered inside the
    //   same BeginBatch/EndBatch block.
    // ----------------------------------------------------------------
    void BeginBatch (ID3D11DeviceContext* context, 
                     DirectX::CXMMATRIX transform = DirectX::XMMatrixIdentity());
    void DrawStringRaw(const char*       text,
                       float             x,
                       float             y,
                       DirectX::FXMVECTOR color = DirectX::Colors::White);
    void DrawStringCenteredRaw(const char*      text,
                               float            centerX,
                               float            y,
                               DirectX::FXMVECTOR color = DirectX::Colors::White);
    void EndBatch();

    // Update stored screen dimensions after a window resize.
    void SetScreenSize(int w, int h) { mScreenW = w; mScreenH = h; }

    bool IsReady() const { return mFont != nullptr; }

    // Release all GPU resources.  Safe to call even if Initialize() was never
    // called or failed.
    void Shutdown();

private:
    std::unique_ptr<DirectX::SpriteFont>  mFont;
    std::unique_ptr<DirectX::SpriteBatch> mSpriteBatch;
    std::unique_ptr<DirectX::CommonStates> mStates;

    int mScreenW = 1280;
    int mScreenH = 720;

    // Bind the viewport explicitly before each SpriteBatch::Begin() call.
    // SpriteBatch queries the RS viewports internally; if another renderer
    // cleared them (e.g. WorldSpriteRenderer), Begin() throws std::runtime_error.
    void BindViewport(ID3D11DeviceContext* context);
};
